# Generated by Django 5.2 on 2025-06-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicles', models.IntegerField(default=0)),
                ('vehicles_crossed', models.IntegerField(default=0)),
                ('simulation_time', models.IntegerField(default=0)),
                ('throughput', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.IntegerField(unique=True)),
                ('red_time', models.IntegerField(default=150)),
                ('yellow_time', models.IntegerField(default=5)),
                ('green_time', models.IntegerField(default=20)),
                ('minimum_time', models.IntegerField(default=10)),
                ('maximum_time', models.IntegerField(default=60)),
                ('current_state', models.CharField(default='red', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('rickshaw', 'Rickshaw'), ('bike', 'Bike')], max_length=10)),
                ('direction', models.CharField(choices=[('right', 'Right'), ('down', 'Down'), ('left', 'Left'), ('up', 'Up')], max_length=10)),
                ('lane', models.IntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('crossed', models.BooleanField(default=False)),
                ('will_turn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
